- name: variables
  hosts: localhost
  become: no
  vars:
  - Course: Terraform
    Trainer:  Sivakumar
    Duration: 15 hours
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "{{Course}} {{Trainer}} {{Duration}}"