- name: variables
  hosts: localhost
  become: no
  vars:
  - Course: Devops
    Trainer:  Siva
    Duration: 120 hours
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "{{Course}} {{Trainer}} {{Duration}}"