- name: var pref check
  hosts: localhost
  become: no 
  vars:
  - WISHES: "from play level GM wishes"
  vars_files:
  - var.yaml 
  vars_prompt:
  - name: WISHES
    prompt: "Enter prompt wishes as ::: from prompt level GM wishes"
  tasks:
  - name: var pref check
    vars:
    - WISHES: "From task level GM wishes"
    ansible.builtin.debug:
      msg: "::::{{WISHES}}"



