- name: datatypes
  hosts: localhost
  become: no 
  vars:
    Course: "Devops with AWS"
    Tools:
      - Linux
      - AWS
      - Ansible
    Exp:
      Devops: 3
      AWS: 2
      Docker: 1
    RealProject: true  

  tasks:
  - name: datatypes
    ansible.builtin.debug:
      msg: "datatypes"