- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense2
    ignore_errors: true


  - name: id expense2 check
    ansible.builtin.debug:
      msg: "hello"  