- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense2
    ignore_errors: true
    register: USER

  - name: user info
    ansible.builtin.debug:
      msg: "{{USER}}"  

  - name: user info catch
    ansible.builtin.command: useradd expense2
    when: $USER.rc != 0    


  - name: id expense2 check
    ansible.builtin.debug:
      msg: "hello"  