- name: conditions
  hosts: localhost
  become: no
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    ignore_errors: true
  - name: debug msg
    ansible.builtin.debug:
      msg: "Hello"  





