- name: Install nginx playleve
  hosts: web 
  become: yes
  tasks:
  - name: install nginx
    #dnf install nginx -y 
    ansible.builtin.dnf: 
      name: nginx
      state: latest
  - name: start nginix
    ansible.builtin.start:
      name: nginx
      state: started
      enable: yes    

      