- name: Install nginx playleve
  hosts: web 
  become: yes
  tasks:
  - name: install nginx
    #dnf install nginx -y 
    ansible.builtin.dnf: 
      name: nginx
      state: latest
  - name: start nginx #systemctl start nginx
                      #systemctl enabled nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
   



      